function formatAssTime(seconds) {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  const cs = Math.floor((seconds % 1) * 100);

  const mm = String(m).padStart(2, '0');
  const ss = String(s).padStart(2, '0');
  const ccs = String(cs).padStart(2, '0');

  return `${h}:${mm}:${ss}.${ccs}`;
}

function generateAss(manifest, songTitle = '') {
  let assContent = `[Script Info]
; Script generated by Lyric Video Generator
Title: Lyric Video
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1280
PlayResY: 720
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arvo,54,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,1,0,0,0,100,100,0,0,1,0,0,5,50,50,30,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  // Display song title if there is at least a 1-second gap before the first lyric segment
  if (songTitle && manifest.length > 0 && manifest[0].startTime >= 1.0) {
    const titleStart = formatAssTime(0);
    const titleEnd = formatAssTime(manifest[0].startTime);
    // Double font size: 54pt * 2 = 108pt. Add 300ms fade transition. Wrap in smart quotes.
    assContent += `Dialogue: 0,${titleStart},${titleEnd},Default,,0,0,0,,{\\fad(300,300)}{\\fs108}“${songTitle}”\n`;
  }

  manifest.forEach((segment) => {
    const start = formatAssTime(segment.startTime);
    const end = formatAssTime(segment.endTime);
    const cleanText = segment.text.replace(/\r?\n/g, '\\N');
    
    // Add fade in and out transition of 300ms using the \fad(300,300) tag
    assContent += `Dialogue: 0,${start},${end},Default,,0,0,0,,{\\fad(300,300)}${cleanText}\n`;
  });

  return assContent;
}

module.exports = { generateAss };
